# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import file_pb2 as file__pb2


class msgServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ligar = channel.unary_unary(
                '/msgService/ligar',
                request_serializer=file__pb2.Vazio.SerializeToString,
                response_deserializer=file__pb2.Estado.FromString,
                )
        self.desligar = channel.unary_unary(
                '/msgService/desligar',
                request_serializer=file__pb2.Vazio.SerializeToString,
                response_deserializer=file__pb2.Estado.FromString,
                )


class msgServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ligar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def desligar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_msgServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ligar': grpc.unary_unary_rpc_method_handler(
                    servicer.ligar,
                    request_deserializer=file__pb2.Vazio.FromString,
                    response_serializer=file__pb2.Estado.SerializeToString,
            ),
            'desligar': grpc.unary_unary_rpc_method_handler(
                    servicer.desligar,
                    request_deserializer=file__pb2.Vazio.FromString,
                    response_serializer=file__pb2.Estado.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'msgService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class msgService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ligar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/msgService/ligar',
            file__pb2.Vazio.SerializeToString,
            file__pb2.Estado.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def desligar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/msgService/desligar',
            file__pb2.Vazio.SerializeToString,
            file__pb2.Estado.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
