# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfile.proto\"\x17\n\x06\x45stado\x12\r\n\x05onOff\x18\x01 \x01(\t\"\x07\n\x05Vazio2C\n\nmsgService\x12\x18\n\x05ligar\x12\x06.Vazio\x1a\x07.Estado\x12\x1b\n\x08\x64\x65sligar\x12\x06.Vazio\x1a\x07.Estadob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ESTADO._serialized_start=14
  _ESTADO._serialized_end=37
  _VAZIO._serialized_start=39
  _VAZIO._serialized_end=46
  _MSGSERVICE._serialized_start=48
  _MSGSERVICE._serialized_end=115
# @@protoc_insertion_point(module_scope)
